### ISSUE TITLE
Can you add a bundler command to allow all in one sort of things

### ISSUE THREAD

**Issue by SolarAquarion** [cedlemo/topinambour#23]

**Comment by SolarAquarion** [comment]
3.2.6 doesn't exist currently, and wouldn't a "static linking" thing with
bundler work better

**Comment by cedlemo** [comment]
@SolarAquarion, I am working on it to see if I can make it works.

**Comment by cedlemo** [comment]
@SolarAquarion, before being able to use a Gemfile for bundler, we first have to make some modifications on the ruby-gnome2 repository see https://github.com/ruby-gnome2/ruby-gnome2/issues/1196.

**Comment by cedlemo** [comment]
@SolarAquarion , could you give it a try.

**Comment by SolarAquarion** [comment]
current directory:
/home/solaraquarion/.bundle/rbx/2.3/ruby-gnome2-f6d1d0478746/atk/dependency-check
/usr/bin/rbx -rrubygems /usr/lib/rubinius/gems/gems/rake-12.3.0/exe/rake
RUBYARCHDIR=/home/solaraquarion/.bundle/rbx/2.3/ruby-gnome2-f6d1d0478746/extensions/x86_64-linux/2.3/ruby-gnome2-f6d1d0478746
RUBYLIBDIR=/home/solaraquarion/.bundle/rbx/2.3/ruby-gnome2-f6d1d0478746/extensions/x86_64-linux/2.3/ruby-gnome2-f6d1d0478746
rake aborted!
LoadError: no such file to load -- pkg-config
core/code_loader.rb:345:in `load_error'
core/code_loader.rb:303:in `require'
core/kernel.rb:861:in `gem_original_require (require)'
/home/solaraquarion/.bundle/rbx/2.3/ruby-gnome2-f6d1d0478746/atk/dependency-check/Rakefile:17:in
`__script__'
core/code_loader.rb:132:in `run_script'
core/code_loader.rb:119:in `load'
core/code_loader.rb:287:in `load'
core/kernel.rb:578:in `load'
core/code_loader.rb:132:in `run_script'
core/code_loader.rb:119:in `load'
core/code_loader.rb:280:in `load_script'
core/loader.rb:667:in `script'
core/loader.rb:852:in `main'
(See full trace by running task with --trace)

rake failed, exit code 1

**Comment by cedlemo** [comment]
@SolarAquarion ,

I have added *pkg-config* ass dependency. Could you try it ?
